# Generated by Django 5.2.9 on 2025-12-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tag_studentprofile_event_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default='Kampüs', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(default='Rektörlük', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
