FROM python:3.13.1-slim

EXPOSE 8001

WORKDIR /app

RUN ln -sf /usr/share/zoneinfo/Europe/Istanbul /etc/localtime

RUN apt-get update && apt-get install -y libpq-dev gcc
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/

RUN pip install --no-cache-dir -r requirements.txt
# BU SATIRI EKLEYİN: Proje dosyalarını içeri kopyalar
COPY . /app/

RUN python manage.py collectstatic --noinput

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]